id = "vala"
name = "Vala"
version = "0.2.0"
schema_version = 1
authors = ["Lleyton Gray <lleyton@fyralabs.com>"]
description = "Vala support."
repository = "https://github.com/FyraLabs/zed-vala"

[grammars.vala]
repository = "https://github.com/RocketRide9/tree-sitter-vala"
commit = "7318a00b7594fe1607326eaaca26ba9b6ab902a4"

[language_servers.vls]
name = "Vala Language Server"
language = "Vala"
