id = "vala"
name = "Vala"
version = "0.2.0"
schema_version = 1
authors = ["Lleyton Gray <lleyton@fyralabs.com>"]
description = "Vala support."
repository = "https://github.com/FyraLabs/zed-vala"

[grammars.vala]
repository = "https://github.com/RocketRide9/tree-sitter-vala"
commit = "a4bed8ffafb342fbecb01eba5c8b95d28dcabb53"

[language_servers.vls]
name = "Vala Language Server"
language = "Vala"
